### ISSUE TITLE
`learn --fail-fast` does not work

### ISSUE THREAD

**Issue by aturkewi** [learn-co/learn-test#27]
`learn --fail-fast` should mimic `rspec --fail-fast` but these flags don't work right now. Also, when this is added back, documentation for it should be added to `learn help test`. 
If students want to only see one spec at a time, they now use `rspec --fail-fast` which will end up leaving heartbeat with less data.

**Comment by adamjonas** [comment]
@ktravers ^^

**Comment by adamjonas** [comment]
++
